import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route('**/api/agent-config', (route) => route.fulfill({ json: { anthropic: true, fal: false } }))
  await page.route('**/api/auth/me', (route) => route.fulfill({ json: { email: 'plan@example.test', loginConfigured: true } }))
})

test('new room, live edits, rename, Library reopen and reload', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/#/library')
  await page.getByRole('button', { name: 'Skip', exact: true }).click()
  await page.getByRole('navigation', { name: 'Workspaces' }).getByRole('button', { name: 'Library', exact: true }).click()
  await page.getByRole('button', { name: 'New floor plan', exact: true }).first().click()
  await expect(page.getByLabel('Plan name')).toBeVisible()
  await expect(page.getByText('Walls 4 · Openings 0 · Rooms 1 · 16.0 m²')).toBeVisible()
  const palette = (await page.getByRole('toolbar', { name: 'Floor plan tools' }).boundingBox())!
  expect(palette.width).toBeLessThanOrEqual(56)
  const canvas = page.getByLabel('2D floor plan', { exact: true })
  const bounds = (await canvas.boundingBox())!
  expect(palette.x + palette.width).toBeLessThanOrEqual(bounds.x)
  const scale = Math.max(14, Math.min(160, (bounds.width - 180) / 4, (bounds.height - 180) / 4))
  const x = bounds.x + bounds.width / 2
  const y = bounds.y + bounds.height / 2 - 2 * scale
  await page.mouse.click(x, y)
  await expect(page.getByLabel('Height', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeDisabled()
  await page.mouse.move(x, y)
  await page.mouse.down()
  await page.mouse.move(x, y + scale / 4, { steps: 3 })
  await page.mouse.up()
  await expect(page.getByText('Walls 4 · Openings 0 · Rooms 1 · 15.0 m²')).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.getByText('Walls 4 · Openings 0 · Rooms 1 · 16.0 m²')).toBeVisible()
  await page.getByRole('button', { name: 'Door', exact: true }).click()
  await page.mouse.move(x, y)
  await page.mouse.click(x, y)
  await expect(page.getByText('Walls 4 · Openings 1 · Rooms 1 · 16.0 m²')).toBeVisible()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Select', exact: true }).click()
  const route = page.url()
  const preview = page.getByLabel('3D preview of the floor plan extrusion')
  await expect(preview).toBeVisible()
  const before = await preview.screenshot()
  await page.getByLabel('All heights', { exact: true }).fill('3')
  await page.getByLabel('Plan name').click()
  await expect.poll(async () => (await preview.screenshot()).equals(before)).toBe(false)
  await page.getByLabel('Plan name').fill('Studio room')
  await page.getByRole('button', { name: '← Library', exact: true }).click()
  await page.getByRole('button', { name: 'Edit plan', exact: true }).click()
  await expect(page).toHaveURL(route)
  await expect(page.getByLabel('Plan name')).toHaveValue('Studio room')
  await expect(page.getByLabel('All heights', { exact: true })).toHaveValue('3')
  await page.reload()
  await expect(page.getByLabel('Plan name')).toHaveValue('Studio room')
  await expect(page.getByLabel('All heights', { exact: true })).toHaveValue('3')
  const left = await page.getByRole('region', { name: '2D floor plan editor' }).boundingBox()
  const field = await page.getByLabel('All heights', { exact: true }).boundingBox()
  expect(field!.x + field!.width).toBeLessThanOrEqual(left!.x + left!.width)
  await page.screenshot({ path: testInfo.outputPath('floor-plan-editor.png') })
  await page.setViewportSize({ width: 768, height: 900 })
  await expect(page.getByLabel('All heights', { exact: true })).toBeVisible()
  const top = (await page.getByRole('region', { name: '2D floor plan editor' }).boundingBox())!
  const bottom = (await preview.boundingBox())!
  expect(bottom.y).toBeGreaterThanOrEqual(top.y + top.height)
  await page.screenshot({ path: testInfo.outputPath('floor-plan-compact.png') })
})


test('Door and Window work on touch without hover and become editable selections', async ({ browser }, testInfo) => {
  const context = await browser.newContext({ hasTouch: true, viewport: { width: 1440, height: 900 } })
  await context.route('**/api/agent-config', (route) => route.fulfill({ json: { anthropic: true, fal: false } }))
  await context.route('**/api/auth/me', (route) => route.fulfill({ json: { email: 'plan@example.test', loginConfigured: true } }))
  const page = await context.newPage()
  try {
    await page.goto('/#/library')
    await page.getByRole('button', { name: 'Skip', exact: true }).click()
    await page.getByRole('navigation', { name: 'Workspaces' }).getByRole('button', { name: 'Library', exact: true }).click()
    await page.getByRole('button', { name: 'New floor plan', exact: true }).first().click()
    const canvas = page.getByLabel('2D floor plan', { exact: true })
    await expect(canvas).toBeVisible()
    const b = (await canvas.boundingBox())!
    const scale = Math.max(14, Math.min(160, (b.width - 180) / 4, (b.height - 180) / 4))
    const cx = b.x + b.width / 2, cy = b.y + b.height / 2
    const toolbar = page.getByRole('toolbar', { name: 'Floor plan tools' })
    await toolbar.getByRole('button', { name: 'Door', exact: true }).click()
    await page.touchscreen.tap(cx, cy - 2 * scale)
    await expect(page.getByText('Walls 4 · Openings 1 · Rooms 1 · 16.0 m²')).toBeVisible()
    await expect(toolbar.getByRole('button', { name: 'Select', exact: true })).toHaveAttribute('aria-pressed', 'true')
    const beforeFlip = await canvas.screenshot()
    await page.getByRole('button', { name: 'Flip swing (F)', exact: true }).click()
    expect((await canvas.screenshot()).equals(beforeFlip)).toBe(false)
    // A second tap edits the door instead of accidentally duplicating it.
    await page.touchscreen.tap(cx, cy - 2 * scale)
    await expect(page.getByText('Walls 4 · Openings 1 · Rooms 1 · 16.0 m²')).toBeVisible()
    await toolbar.getByRole('button', { name: 'Window', exact: true }).click()
    await page.touchscreen.tap(cx - 2 * scale, cy)
    await expect(page.getByText('Walls 4 · Openings 2 · Rooms 1 · 16.0 m²')).toBeVisible()
    await expect(page.getByLabel('Sill', { exact: true })).toHaveValue('0.9')
    await expect(page.getByRole('button', { name: 'Flip swing (F)', exact: true })).toHaveCount(0)
    await page.getByLabel('Sill', { exact: true }).fill('3')
    await expect(page.getByText('The opening is too tall for this wall. Reduce its height or sill.')).toBeVisible()
    await page.getByLabel('Width', { exact: true }).click()
    await expect(page.getByLabel('Sill', { exact: true })).toHaveValue('0.9')
    await toolbar.getByRole('button', { name: 'Window', exact: true }).click()
    await page.touchscreen.tap(cx, cy - 2 * scale)
    await expect(page.getByText('This overlaps another opening. Choose a free part of the wall.')).toBeVisible()
    await expect(page.getByText('Walls 4 · Openings 2 · Rooms 1 · 16.0 m²')).toBeVisible()
    await toolbar.getByRole('button', { name: 'Select', exact: true }).click()
    await page.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByText('Saved to Library', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: '← Library', exact: true }).click()
    await page.getByRole('button', { name: 'Edit plan', exact: true }).click()
    await expect(page.getByText('Walls 4 · Openings 2 · Rooms 1 · 16.0 m²')).toBeVisible()
    await page.screenshot({ path: testInfo.outputPath('doors-windows.png'), animations: 'disabled' })
  } finally { await context.close() }
})
